// export const classColors: Record<string, string> = {
//   alchemist: 'bg-yellow-500',
//   barbarian: 'bg-red-500',
//   bard: 'bg-purple-500',
//   champion: 'bg-blue-700',
//   cleric: 'bg-yellow-400',
//   druid: 'bg-green-600',
//   fighter: 'bg-blue-600',
//   gunslinger: 'bg-amber-800',
//   inventor: 'bg-orange-500',
//   investigator: 'bg-teal-500',
//   kineticist: 'bg-red-600',
//   magus: 'bg-indigo-500',
//   monk: 'bg-green-400',
//   oracle: 'bg-lime-800',
//   psychic: 'bg-purple-500',
//   ranger: 'bg-green-600',
//   rogue: 'bg-gray-500',
//   sorcerer: 'bg-pink-500',
//   summoner: 'bg-purple-500',
//   swashbuckler: 'bg-orange-400',
//   thaumaturge: 'bg-indigo-700',
//   witch: 'bg-purple-600',
//   wizard: 'bg-blue-500',
// };

export const classColors: Record<string, string> = {
  alchemist: 'text-yellow-500',
  barbarian: 'text-red-500',
  bard: 'text-purple-500',
  champion: 'text-blue-700',
  cleric: 'text-yellow-400',
  druid: 'text-green-600',
  fighter: 'text-blue-600',
  gunslinger: 'text-amber-800',
  inventor: 'text-orange-500',
  investigator: 'text-teal-500',
  kineticist: 'text-red-600',
  magus: 'text-indigo-500',
  monk: 'text-green-400',
  oracle: 'text-lime-800',
  psychic: 'text-purple-500',
  ranger: 'text-green-600',
  rogue: 'text-gray-500',
  sorcerer: 'text-pink-500',
  summoner: 'text-purple-500',
  swashbuckler: 'text-orange-400',
  thaumaturge: 'text-indigo-700',
  witch: 'text-purple-600',
  wizard: 'text-blue-500',
};